name: Pipeline

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        env:
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew clean build publish

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            build/libs/*.jar